### ISSUE TITLE
Not able to decompress large strings

### ISSUE THREAD

**Issue by basithvofox** [takagi-denki/lzstring-swift#11]
I am getting this error while decompressing large strings.
2022-02-06 14:10:06.835149+0530 Test[3704:1771835] Swift/Integers.swift:3447: Fatal error: Not enough bits to represent the passed value

The code I have tries is 
 let newString = decompressFromUTF16(input: myString)
myString is very large LZ string from server which is sized around 1-2 MB.

![Screenshot 2022-02-06 at 2 11 25 PM](https://user-images.githubusercontent.com/92799605/152673585-432bf74b-22d5-4f28-8282-ba139ff3ad8c.png)

**Comment by Ibrahimhass** [comment]
@mtakagi @gitter-badger Please review my PR which focuses on fixing this issue.
https://github.com/takagi-denki/lzstring-swift/pull/12
Your feedback is welcome.
